spring:
  application:
    name: laumiley-modas-api
  datasource:
    url: ${LAUMILEY_DB}
    username: ${AIVEN_DB_USER}
    password: ${AIVEN_DB_PASS}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: ${LAUMILEY_MEDIA_MAX_FILE_SIZE:10MB}
      max-request-size: ${LAUMILEY_MEDIA_MAX_REQUEST_SIZE:50MB}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${LAUMILEY_OAUTH_CLIENT_ID}
            client-secret: ${LAUMILEY_OAUTH_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1